### ISSUE TITLE
4레벨 과제 코드리뷰

### ISSUE THREAD

**Issue by mansooonuna** [mansooonuna/hh99-spring_post_lv4#1]
개인적으로 4레벨 과제에서 가장 중요한 것은 `스프링 시큐리티` 를 적용하는 것이라고 생각했습니다.
과제 초반에는 생각보다 수정할 내용이 많이 없어서 제대로 적용이 되었는지 의문이었습니다.
더 많은 자료를 찾아보는 중에 우리 코드에서는 여전히 인증을 할 때 HttpServlet으로 사용자 정보를 전달하고 있다는 것을 알았습니다.
```
    @PostMapping("/post")
    public PostResponseDto createPost(@RequestBody PostRequestDto postRequestDto, @AuthenticationPrincipal UserDetailsImpl userDetails) {
        return postService.createPost(postRequestDto, userDetails.getUser());
    }
```
위 코드는 PostController 에 있는 `게시글 작성 API` 입니다.  HttpServletRequest 를 사용하여 User 의 정보를 넘겨주던 것을 수정했습니다. 

그리고 시큐리티를 사용하기 위해 WebSecurityConfig를 추가하여 내용을 추가해주었습니다.
https://github.com/mansooonuna/hh99-spring_post_lv4/blob/master/src/main/java/com/sparta/spring_post/config/WebSecurityConfig.java 

3레벨 과제와 비교했을 때 차이점은 이 내용들이라고 생각합니다만, 스프링 시큐리티에 대해 아직 완전히 알지 못해서 잘 적용되었는지 아직도 모르겠습니다.

**Comment by taetoo** [comment]
일단 레벨 4까지 진행하시느라 정말 수고 많으셨습니다. 🙇🏻
게더 순회때 이미 말씀드렸지만, 현재 시큐리티 설정 코드 상에 큰 문제는 없이 잘 작성되었다고 보여집니다.
다만 인증과 인가에 대한 핸들링 하는 부분은 따로 구분하여 확실하게 역할을 나눠 볼 수 있게 만들면 좋겠다는 피드백을 드렸습니다.
하나의 클래스로 묶인다고 기능상 달라질 것은 없지만, 앞으로 확장성을 생각하신다면 나눠보시면 좋을 것 같습니다!
